import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { SiteProvider } from "~/components/site-context";
import { Toaster } from "~/components/ui/sonner";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable} dark`} lang="en">
			<body>
				<div className="fixed inset-0 -z-10 overflow-hidden bg-gray-950">
					<div className="absolute -top-40 -left-20 h-[500px] w-[500px] rounded-full bg-blue-600/10 blur-3xl" />
					<div className="absolute -right-20 -bottom-40 h-[500px] w-[500px] rounded-full bg-purple-600/8 blur-3xl" />
				</div>
				<TRPCReactProvider>
					<SiteProvider>
						<SessionProvider>{children}</SessionProvider>
					</SiteProvider>
				</TRPCReactProvider>
				<Toaster position="bottom-right" richColors />
			</body>
		</html>
	);
}
